import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import ProgressBar from "@/components/custom/ProgressBar";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Visitor Dashboard",
  description: "Generated by GEHU Boys",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` antialiased`}>
      <Suspense fallback={null}>
        <ProgressBar />
      </Suspense>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
